<?php
   session_start();
       if(!isset($_SESSION['userlogin'])){
           header("Location: login.php");
       }
   
       if(isset($_GET['logout'])){
           session_destroy();
           unset($_SESSION);
           header("Location: login.php");
           
       }
       if($_SESSION['userlogin']['type'] !== "QS"){
        // isn't admin, redirect them to a different page
        header("Location: index.php");
    }
   ?>
<?php
   require_once('config.php');
   ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="quotationstyle.css" />
        <title>Quotation</title>
    </head>
    <body>
        <div class="quotationContainer">
            <div class="quote">
                <div class="heading">
                    <div class="heading-logo-info">
                        <div class="logo">
                            <img src="logo.png" alt="MA Tracker Logo">
                            <br>
                        </div>   
                        <div class="QuoteInfo">
                            <h3>Quotation</h3> 
                            <p>
                                <span>Date:</span>
                                <?php
                                $date = $_POST['date'];
                                echo "<span>$date</span>";
                                ?>
                                
                            </p>
                            <br>
                            <p>
                                <span>Supplier:</span>
                                <?php
                                $sname = $_POST['sname'];
                                echo "<span>$sname</span>";
                                ?>
                                
                            </p>
                        </div>
                    </div>
                    <br>
                    <div class="custBilling">
                        <h4>Customer Information</h4>
                        <br> 
                        <?php
                        $compName = $_SESSION['userlogin']['companyname'];
                        $fname =$_SESSION['userlogin']['firstname'];
                        $lname =$_SESSION['userlogin']['lastname'];
                        $email = $_SESSION['userlogin']['email'];
                        $pnum = $_SESSION['userlogin']['phonenumber'];
                        echo"
                        <p>Company's Name: $compName</p> 
                        <p>Name: $fname $lname</p>
                        <p>Email Address: $email</p> 
                        <p>Tel.: $pnum</p>
                        ";
                        ?>
                    </div>
                    <br>
                </div>
                <br>
                <div class="tabBody">
                    <table>
                        <tr>
                            <th>Item Name.</th>
                            <th>Item Description</th>
                            <th>Quantity</th>
                            <th>Unit Price</th>
                            <th>Total</th>
                          </tr>
                          <tr>
                          <?php
                                $pname = $_POST['pname'];
                                $pdes = $_POST['pdes'];
                                $punit = $_POST['punit'];
                                $pcost = $_POST['pcost'];
                                $pquan = $_POST['quantity'];
                                $ptotal = $pquan*$pcost;
                                echo $pname;

                                echo "<td>$pname</td>
                                      <td>$pdes</td>
                                      <td>$pquan</td>
                                      <td>$$pcost/$punit</td>
                                      <td>$$ptotal</td>";
                                ?>
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <th>Grand Total</td>
                            <?php
                            echo"<td>$$ptotal</td>";
                            ?>
                          </tr>
                    </table>
                </div>
                <br>
                <footer>
                    <p>
                    <form action="index.php">
                        <input type="submit" value="Go Home" />
                    </form>

                        <span> Generated by MA Tracker 2022 </span>
                    </p> 
                </footer>
            </div>
        </div>

    </body>
    </html>